### ISSUE TITLE
Phonegap.js

### ISSUE THREAD

**Issue by subtiv** [jvcleave-archive/ofxWebSimpleGuiToo-for-iPhone#1]
When i try to run the "phoneGapApp" i get the following error: "cp: /javascripts/phonegap.js: No such file or directory"
Am i doing something wrong? 
[EDIT]: I tried both on OF 06 and OF 07 in Xcode3 and Xcode 4

**Comment by jvcleave** [comment]
You are probably missing PhoneGap. http://phonegap.com/

**Comment by subtiv** [comment]
Ow, sorry about that! Thanks
